version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    image: nginx:latest
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html

  jmeter:
    image: justb4/jmeter:latest
    container_name: jmeter
    volumes:
      - ./jmeter:/jmeter
    entrypoint: ["jmeter", "-n", "-t", "/jmeter/test-plan.jmx", "-l", "/jmeter/results.jtl"]

volumes:
  postgres_data:
  mongo_data:
  redis_data:
